#!/usr/bin/env node
/**
 * Auto-generate `tokens/sandbox/snapshots.parity.json` from on-disk PNGs.
 *
 * Walks the iOS and Android snapshot directories, classifies every story id
 * into one of three buckets:
 *   - `shared`       — present in BOTH iOS and Android
 *   - `ios_only`     — present in iOS but not Android
 *   - `android_only` — present in Android but not iOS
 *
 * The generated manifest is the single source of truth for
 * `scripts/snapshots/check.ts` and `scripts/snapshots/parity-coverage.ts`.
 *
 * Idempotent: running twice produces no diff. The `generated` timestamp is
 * preserved across runs when the structural contents (shared/ios_only/
 * android_only arrays) are unchanged.
 *
 * Usage: pnpm snapshots:sync-manifest
 */

import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, '../..')

const IOS_SNAPSHOT_DIR = join(ROOT, 'ios/LaneShadowTests/__Snapshots__/StorySnapshotTests')
const ANDROID_SNAPSHOT_DIR = join(
  ROOT,
  'android/app/src/androidTest/screenshots/AllStoriesSnapshotTest',
)
const MANIFEST_PATH = join(ROOT, 'tokens/sandbox/snapshots.parity.json')

const MANIFEST_VERSION = '2'
const MANIFEST_NOTE = 'Auto-generated by `pnpm snapshots:sync-manifest`. Do not hand-edit.'

// Canonical filename format: {storyId}.{theme}.png
// e.g. atoms.button.primary.light.png
const SNAPSHOT_FILENAME_RE = /^(.+)\.(light|dark)\.png$/

interface ParityManifest {
  version: string
  generated: string
  _note: string
  shared: string[]
  ios_only: string[]
  android_only: string[]
}

/**
 * Walk a snapshot directory and return the unique set of canonical story IDs.
 * Files that don't match the canonical `{storyId}.{theme}.png` regex are
 * skipped with a warning so that legacy artifacts don't crash sync.
 */
function collectStoryIds(snapshotDir: string, label: string): Set<string> {
  const ids = new Set<string>()
  if (!existsSync(snapshotDir)) {
    console.warn(`⚠️  ${label} snapshot dir not found: ${snapshotDir}`)
    return ids
  }

  const files = readdirSync(snapshotDir).filter((f) => f.endsWith('.png'))
  for (const file of files) {
    const match = file.match(SNAPSHOT_FILENAME_RE)
    if (!match) {
      console.warn(`⚠️  ${label}: skipping non-canonical filename: ${file}`)
      continue
    }
    const [, storyId] = match
    ids.add(storyId)
  }
  return ids
}

function classify(
  iosIds: Set<string>,
  androidIds: Set<string>,
): { shared: string[]; ios_only: string[]; android_only: string[] } {
  const shared: string[] = []
  const iosOnly: string[] = []
  const androidOnly: string[] = []

  for (const id of iosIds) {
    if (androidIds.has(id)) {
      shared.push(id)
    } else {
      iosOnly.push(id)
    }
  }
  for (const id of androidIds) {
    if (!iosIds.has(id)) {
      androidOnly.push(id)
    }
  }

  shared.sort()
  iosOnly.sort()
  androidOnly.sort()

  return { shared, ios_only: iosOnly, android_only: androidOnly }
}

/**
 * Load the existing manifest, if any. Used to preserve `generated` timestamp
 * across runs that produce no structural changes (idempotency property).
 */
function loadExistingManifest(): ParityManifest | null {
  if (!existsSync(MANIFEST_PATH)) return null
  try {
    const raw = readFileSync(MANIFEST_PATH, 'utf-8')
    return JSON.parse(raw) as ParityManifest
  } catch (err) {
    console.warn(
      `⚠️  Could not parse existing manifest (will regenerate from scratch): ${
        err instanceof Error ? err.message : String(err)
      }`,
    )
    return null
  }
}

function structurallyEqual(
  a: ParityManifest | null,
  b: Omit<ParityManifest, 'generated'>,
): boolean {
  if (!a) return false
  return (
    a.version === b.version &&
    a._note === b._note &&
    JSON.stringify(a.shared) === JSON.stringify(b.shared) &&
    JSON.stringify(a.ios_only) === JSON.stringify(b.ios_only) &&
    JSON.stringify(a.android_only) === JSON.stringify(b.android_only)
  )
}

function main(): void {
  console.log('🔄 Syncing snapshot parity manifest from disk...\n')

  const iosIds = collectStoryIds(IOS_SNAPSHOT_DIR, 'iOS')
  const androidIds = collectStoryIds(ANDROID_SNAPSHOT_DIR, 'Android')

  const buckets = classify(iosIds, androidIds)

  const proposed: Omit<ParityManifest, 'generated'> = {
    version: MANIFEST_VERSION,
    _note: MANIFEST_NOTE,
    shared: buckets.shared,
    ios_only: buckets.ios_only,
    android_only: buckets.android_only,
  }

  const existing = loadExistingManifest()
  const generated =
    existing && structurallyEqual(existing, proposed)
      ? existing.generated
      : new Date().toISOString()

  // Schema-key order matters for stable diffs. Build in the canonical order:
  // version → generated → _note → shared → ios_only → android_only
  const manifest: ParityManifest = {
    version: proposed.version,
    generated,
    _note: proposed._note,
    shared: proposed.shared,
    ios_only: proposed.ios_only,
    android_only: proposed.android_only,
  }

  // 2-space indent, trailing newline — matches the existing manifest style.
  const json = `${JSON.stringify(manifest, null, 2)}\n`
  writeFileSync(MANIFEST_PATH, json, 'utf-8')

  const total = manifest.shared.length + manifest.ios_only.length + manifest.android_only.length
  console.log('✅ Manifest synced')
  console.log(`   Path:         ${MANIFEST_PATH}`)
  console.log(`   iOS PNG ids:  ${iosIds.size}`)
  console.log(`   Android ids:  ${androidIds.size}`)
  console.log(`   shared:       ${manifest.shared.length}`)
  console.log(`   ios_only:     ${manifest.ios_only.length}`)
  console.log(`   android_only: ${manifest.android_only.length}`)
  console.log(`   total tracked:${total}`)
  if (existing && structurallyEqual(existing, proposed)) {
    console.log('   (no structural change — `generated` timestamp preserved)')
  }
}

main()
