#!/usr/bin/env tsx

/**
 * UC-SBX-03-ios Fixture Generation
 *
 * Generates Swift fixtures from JSON files.
 * Emits: tokens/platforms/swift/Sources/LaneShadowMocks/Generated/Fixtures.swift
 *
 * Source: tokens/sandbox/fixtures/*.fixtures.json
 */

import * as fs from 'node:fs'
import * as path from 'node:path'

interface FixtureData {
  [variant: string]: any[]
}

interface Route {
  id: string
  name: string
  via: string
  distance: number
  estimatedTime: number
  climb: number
  scenicScore: number
  difficulty: string
  polyline: string
  variant: string
}

interface User {
  id: string
  name: string
  handle: string
  avatarUrl: string | null
  bio: string
}

interface Session {
  id: string
  title: string
  preview: string
  meta: string
  when: string
  active: boolean
  routeIds: string[]
  createdAt: string
}

interface NavigatorMessage {
  id: string
  sessionId: string
  body: string
  timestamp: string
  kind: 'prompt' | 'response'
  attachments: any[] | null
  detail: any | null
  pinned: boolean
}

interface WeatherTimeline {
  hour: string
  temperature: number
  condition: string
}

interface PlanningPhase {
  id: string
  label: string
  status: string
}

interface SuggestionChip {
  id: string
  label: string
}

const FIXTURES_DIR = path.resolve(__dirname, '../sandbox/fixtures')
const OUTPUT_FILE = path.resolve(
  __dirname,
  '../platforms/swift/Sources/LaneShadowMocks/Generated/Fixtures.swift',
)

function loadFixtures<T>(filename: string): FixtureData {
  const filepath = path.join(FIXTURES_DIR, filename)
  const content = fs.readFileSync(filepath, 'utf-8')
  return JSON.parse(content)
}

function toSwiftString(value: any): string {
  if (value === null) return 'nil'
  if (typeof value === 'string') return `"${value.replace(/"/g, '\\"')}"`
  if (typeof value === 'number') return value.toString()
  if (typeof value === 'boolean') return value ? 'true' : 'false'
  if (Array.isArray(value)) return `[${value.map(toSwiftString).join(', ')}]`
  if (typeof value === 'object') {
    const entries = Object.entries(value).map(([k, v]) => `${k}: ${toSwiftString(v)}`)
    return `[${entries.join(', ')}]`
  }
  return 'nil'
}

function generateSwiftFile(): string {
  // We'll generate Swift code that loads JSON from bundle resources
  return `// This file is auto-generated by UC-SBX-03-ios fixture generation
// DO NOT EDIT BY HAND
// Run: pnpm fixtures:generate

import Foundation

/// Generated fixture data for Navigator screens.
public enum Mocks {
    private static let decoder = JSONDecoder()

    public static let routes: [Route] = loadVariant("routes", variant: "default")
    public static let users: [User] = loadVariant("users", variant: "default")
    public static let sessions: [Session] = loadVariant("sessions", variant: "default")
    public static let navigatorMessages: [NavigatorMessage] = loadVariant("navigator-messages", variant: "default")
    public static let weatherTimelines: [WeatherTimeline] = loadVariant("weather-timelines", variant: "default")
    public static let planningPhases: [PlanningPhase] = loadVariant("planning-phases", variant: "default")
    public static let suggestionChips: [SuggestionChip] = loadVariant("suggestion-chips", variant: "default")

    // Variant accessors
    public enum Routes {
        public static let \`default\` = Mocks.routes
        public static let empty: [Route] = []
        public static let overflow: [Route] = loadVariant("routes", variant: "overflow")
        public static let longCopy: [Route] = loadVariant("routes", variant: "long-copy")
    }

    public enum Users {
        public static let \`default\` = Mocks.users
        public static let empty: [User] = []
        public static let overflow: [User] = loadVariant("users", variant: "overflow")
        public static let longCopy: [User] = loadVariant("users", variant: "long-copy")
    }

    public enum Sessions {
        public static let \`default\` = Mocks.sessions
        public static let empty: [Session] = []
        public static let overflow: [Session] = loadVariant("sessions", variant: "overflow")
        public static let longCopy: [Session] = loadVariant("sessions", variant: "long-copy")
    }

    public enum NavigatorMessages {
        public static let \`default\` = Mocks.navigatorMessages
        public static let empty: [NavigatorMessage] = []
        public static let overflow: [NavigatorMessage] = loadVariant("navigator-messages", variant: "overflow")
        public static let longCopy: [NavigatorMessage] = loadVariant("navigator-messages", variant: "long-copy")
    }

    public enum WeatherTimelines {
        public static let \`default\` = Mocks.weatherTimelines
        public static let empty: [WeatherTimeline] = []
        public static let overflow: [WeatherTimeline] = loadVariant("weather-timelines", variant: "overflow")
        public static let longCopy: [WeatherTimeline] = loadVariant("weather-timelines", variant: "long-copy")
    }

    public enum PlanningPhases {
        public static let \`default\` = Mocks.planningPhases
        public static let empty: [PlanningPhase] = []
        public static let overflow: [PlanningPhase] = loadVariant("planning-phases", variant: "overflow")
        public static let longCopy: [PlanningPhase] = loadVariant("planning-phases", variant: "long-copy")
    }

    public enum SuggestionChips {
        public static let \`default\` = Mocks.suggestionChips
        public static let empty: [SuggestionChip] = []
        public static let overflow: [SuggestionChip] = loadVariant("suggestion-chips", variant: "overflow")
        public static let longCopy: [SuggestionChip] = loadVariant("suggestion-chips", variant: "long-copy")
    }
}

private func loadVariant<T: Decodable>(_ name: String, variant: String) -> [T] {
    guard let url = Bundle.module.url(forResource: "fixtures/\\(name).\\(variant)", withExtension: "json"),
          let data = try? Data(contentsOf: url),
          let decoded = try? Mocks.decoder.decode([T].self, from: data) else {
        print("⚠️ Failed to load fixture: \\(name).\\(variant).json")
        return []
    }
    return decoded
}

// MARK: - Fixture Models

public struct Route: Codable, Sendable {
    public let id: String
    public let name: String
    public let via: String
    public let distance: Double
    public let estimatedTime: Double
    public let climb: Double
    public let scenicScore: Int
    public let difficulty: String
    public let polyline: String
    public let variant: String

    public init(id: String, name: String, via: String, distance: Double, estimatedTime: Double, climb: Double, scenicScore: Int, difficulty: String, polyline: String, variant: String) {
        self.id = id
        self.name = name
        self.via = via
        self.distance = distance
        self.estimatedTime = estimatedTime
        self.climb = climb
        self.scenicScore = scenicScore
        self.difficulty = difficulty
        self.polyline = polyline
        self.variant = variant
    }
}

public struct User: Codable, Sendable {
    public let id: String
    public let name: String
    public let handle: String
    public let avatarUrl: String?
    public let bio: String

    public init(id: String, name: String, handle: String, avatarUrl: String?, bio: String) {
        self.id = id
        self.name = name
        self.handle = handle
        self.avatarUrl = avatarUrl
        self.bio = bio
    }
}

public struct Session: Codable, Sendable {
    public let id: String
    public let title: String
    public let preview: String
    public let meta: String
    public let when: String
    public let active: Bool
    public let routeIds: [String]
    public let createdAt: String

    public init(id: String, title: String, preview: String, meta: String, when: String, active: Bool, routeIds: [String], createdAt: String) {
        self.id = id
        self.title = title
        self.preview = preview
        self.meta = meta
        self.when = when
        self.active = active
        self.routeIds = routeIds
        self.createdAt = createdAt
    }
}

public struct NavigatorMessage: Codable, Sendable {
    public let id: String
    public let sessionId: String
    public let body: String
    public let timestamp: String
    public let kind: String
    public let attachments: [RouteAttachment]?
    public let detail: String?
    public let pinned: Bool

    public init(id: String, sessionId: String, body: String, timestamp: String, kind: String, attachments: [RouteAttachment]?, detail: String?, pinned: Bool) {
        self.id = id
        self.sessionId = sessionId
        self.body = body
        self.timestamp = timestamp
        self.kind = kind
        self.attachments = attachments
        self.detail = detail
        self.pinned = pinned
    }
}

public struct RouteAttachment: Codable, Sendable {
    public let routeId: String
    public let variant: String
    public let isBest: Bool
    public let weather: WeatherInfo?
    public let scenic: Int?
    public let includesFavorite: Bool?
    public let includesFavoriteLabel: String?

    public init(routeId: String, variant: String, isBest: Bool, weather: WeatherInfo?, scenic: Int?, includesFavorite: Bool?, includesFavoriteLabel: String?) {
        self.routeId = routeId
        self.variant = variant
        self.isBest = isBest
        self.weather = weather
        self.scenic = scenic
        self.includesFavorite = includesFavorite
        self.includesFavoriteLabel = includesFavoriteLabel
    }
}

public struct WeatherInfo: Codable, Sendable {
    public let condition: String
    public let label: String

    public init(condition: String, label: String) {
        self.condition = condition
        self.label = label
    }
}

public struct WeatherTimeline: Codable, Sendable {
    public let hour: String
    public let temperature: Int
    public let condition: String

    public init(hour: String, temperature: Int, condition: String) {
        self.hour = hour
        self.temperature = temperature
        self.condition = condition
    }
}

public struct PlanningPhase: Codable, Sendable {
    public let id: String
    public let label: String
    public let status: String

    public init(id: String, label: String, status: String) {
        self.id = id
        self.label = label
        self.status = status
    }
}

public struct SuggestionChip: Codable, Sendable {
    public let id: String
    public let label: String

    public init(id: String, label: String) {
        self.id = id
        self.label = label
    }
}
`
}

function copyFixtureFiles() {
  const fixturesDir = path.resolve(__dirname, '../sandbox/fixtures')
  const outputDir = path.resolve(
    __dirname,
    '../platforms/swift/Sources/LaneShadowMocks/Resources/fixtures',
  )

  // Ensure output directory exists
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true })
  }

  // Copy and transform fixture files
  const fixtureFiles = [
    'routes.fixtures.json',
    'users.fixtures.json',
    'sessions.fixtures.json',
    'navigator-messages.fixtures.json',
    'weather-timelines.fixtures.json',
    'planning-phases.fixtures.json',
    'suggestion-chips.fixtures.json',
  ]

  for (const fixtureFile of fixtureFiles) {
    const filepath = path.join(fixturesDir, fixtureFile)
    const content = fs.readFileSync(filepath, 'utf-8')
    const data = JSON.parse(content)

    // Split variants into separate files
    for (const [variant, items] of Object.entries(data)) {
      const baseName = fixtureFile.replace('.fixtures.json', '')
      const outputFile = path.join(outputDir, `${baseName}.${variant}.json`)
      fs.writeFileSync(outputFile, JSON.stringify(items, null, 2), 'utf-8')
    }
  }

  console.log(`✓ Copied fixture files to ${outputDir}`)
}

function main() {
  console.log('Generating Swift fixtures from JSON...')

  // Copy and transform fixture files
  copyFixtureFiles()

  // Generate Swift code
  const swiftCode = generateSwiftFile()

  // Ensure output directory exists
  const outputDir = path.dirname(OUTPUT_FILE)
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true })
  }

  // Write generated file
  fs.writeFileSync(OUTPUT_FILE, swiftCode, 'utf-8')

  console.log(`✓ Generated ${OUTPUT_FILE}`)
  console.log('  Run: pnpm fixtures:generate')
}

main()
