// GENERATED by tokens/scripts/generate.ts — do not edit by hand
// input-hash: 685825c7

export const mapboxStyleUrls = {
  light: 'mapbox://styles/laneshadow/clxwarm01', // Warm-paper topographic map · Copper day theme
  dark: 'mapbox://styles/laneshadow/clxnight02', // Warm-ink night map · Copper dark theme
} as const

export type MapboxStyleUrls = typeof mapboxStyleUrls
