// GENERATED by tokens/scripts/generate.ts — do not edit by hand
// input-hash: 873e5537

export const tokens = {
  color: {
    surface: {
      primary: {
        light: '#F8F7F6',
        dark: '#221810',
      },
      card: {
        light: '#FDFBF8',
        dark: '#2D2218',
      },
      inset: {
        light: '#F2EFED',
        dark: '#362A1F',
      },
      overlay: {
        light: 'rgba(253,251,248,0.92)',
        dark: 'rgba(45,34,24,0.92)',
      },
      glass: {
        light: 'rgba(253,251,248,0.72)',
        dark: 'rgba(45,34,24,0.72)',
      },
      scrim: {
        light: 'rgba(34,24,16,0.35)',
        dark: 'rgba(10,6,3,0.50)',
      },
      'scrim-soft': {
        light: 'rgba(34,24,16,0.18)',
        dark: 'rgba(10,6,3,0.28)',
      },
    },
    content: {
      primary: {
        light: '#1E1A16',
        dark: '#F2EEE8',
      },
      secondary: {
        light: '#49454F',
        dark: '#CAC4D0',
      },
      tertiary: {
        light: '#6B6460',
        dark: '#9CA3AF',
      },
      subtle: {
        light: '#9CA3AF',
        dark: '#6B6460',
      },
      onSignal: {
        light: '#FFFFFF',
        dark: '#FFFFFF',
      },
    },
    signal: {
      default: {
        light: '#EE7C2B',
        dark: '#EE7C2B',
      },
      pressed: {
        light: '#9E4A22',
        dark: '#9E4A22',
      },
      tint: {
        light: '#F9D5B5',
        dark: '#F9D5B5',
      },
      whisper: {
        light: '#FCE8D4',
        dark: '#FCE8D4',
      },
    },
    role: {
      agent: {
        default: {
          light: '#EE7C2B',
          dark: '#EE7C2B',
        },
      },
      user: {
        default: {
          light: '#F2EFED',
          dark: '#F2EFED',
        },
      },
      system: {
        default: {
          light: '#E5DED9',
          dark: '#E5DED9',
        },
      },
    },
    weather: {
      clear: {
        default: {
          light: '#E6A52A',
          dark: '#E6A52A',
        },
        tint: {
          light: '#FBEFCF',
          dark: '#FBEFCF',
        },
      },
      rain: {
        default: {
          light: '#4A86BE',
          dark: '#4A86BE',
        },
        tint: {
          light: '#DBEAF4',
          dark: '#DBEAF4',
        },
      },
      wind: {
        default: {
          light: '#6B7B8F',
          dark: '#6B7B8F',
        },
        tint: {
          light: '#E1E6EC',
          dark: '#E1E6EC',
        },
      },
      storm: {
        default: {
          light: '#5E3FAE',
          dark: '#5E3FAE',
        },
        tint: {
          light: '#E3DCF2',
          dark: '#E3DCF2',
        },
      },
      hot: {
        default: {
          light: '#C9423C',
          dark: '#C9423C',
        },
        tint: {
          light: '#F5D8D6',
          dark: '#F5D8D6',
        },
      },
      cold: {
        default: {
          light: '#3A8BE3',
          dark: '#3A8BE3',
        },
        tint: {
          light: '#D6E5F7',
          dark: '#D6E5F7',
        },
      },
    },
    route: {
      best: {
        light: '#EE7C2B',
        dark: '#EE7C2B',
      },
      alt1: {
        light: '#4D8470',
        dark: '#4D8470',
      },
      alt2: {
        light: '#6B7B8F',
        dark: '#6B7B8F',
      },
    },
    status: {
      info: {
        default: {
          light: '#3A8BE3',
          dark: '#3A8BE3',
        },
      },
      success: {
        default: {
          light: '#4D8470',
          dark: '#4D8470',
        },
      },
      warning: {
        default: {
          light: '#C46F1B',
          dark: '#C46F1B',
        },
      },
      error: {
        default: {
          light: '#C9423C',
          dark: '#C9423C',
        },
      },
    },
    border: {
      default: {
        light: '#E5DED9',
        dark: 'rgba(242,238,232,0.12)',
      },
      subtle: {
        light: '#EDE7E1',
        dark: 'rgba(242,238,232,0.07)',
      },
      strong: {
        light: '#C9BDB3',
        dark: 'rgba(242,238,232,0.22)',
      },
      focus: {
        light: '#EE7C2B',
        dark: '#EE7C2B',
      },
      glass: {
        light: 'rgba(255,255,255,0.55)',
        dark: 'rgba(242,238,232,0.22)',
      },
    },
    action: {
      primary: {
        default: {
          light: '#EE7C2B',
          dark: '#EE7C2B',
        },
        hover: {
          light: '#F3A164',
          dark: '#F3A164',
        },
        pressed: {
          light: '#9E4A22',
          dark: '#9E4A22',
        },
      },
      secondary: {
        default: {
          light: '#FCE8D4',
          dark: '#FCE8D4',
        },
        hover: {
          light: '#F9D5B5',
          dark: '#F9D5B5',
        },
        pressed: {
          light: '#F3A164',
          dark: '#F3A164',
        },
      },
    },
  },
  typography: {
    opinion: {
      $comment: {
        family: 'Geist',
        weight: undefined,
        size: undefined,
        lineHeight: NaN,
      },
      xl: {
        family: 'Newsreader',
        weight: 400,
        size: 30,
        lineHeight: 1.12,
      },
      lg: {
        family: 'Newsreader',
        weight: 400,
        size: 22,
        lineHeight: 1.18,
      },
      md: {
        family: 'Newsreader',
        weight: 400,
        size: 17,
        lineHeight: 1.32,
      },
      sm: {
        family: 'Newsreader',
        weight: 400,
        size: 14,
        lineHeight: 1.45,
      },
    },
    ui: {
      $comment: {
        '0': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '1': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '2': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '3': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '4': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '5': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '6': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '7': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '8': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '9': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '10': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '11': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '12': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '13': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '14': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '15': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '16': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '17': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '18': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '19': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '20': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '21': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '22': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '23': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '24': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '25': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '26': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '27': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '28': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '29': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '30': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '31': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '32': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '33': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '34': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '35': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '36': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '37': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '38': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '39': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '40': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '41': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '42': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '43': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '44': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '45': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '46': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '47': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '48': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '49': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '50': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '51': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '52': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '53': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '54': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '55': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '56': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '57': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '58': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '59': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '60': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '61': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '62': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '63': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '64': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '65': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '66': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '67': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '68': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '69': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '70': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '71': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '72': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '73': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '74': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '75': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '76': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '77': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '78': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '79': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '80': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '81': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '82': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '83': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '84': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '85': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '86': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '87': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '88': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '89': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '90': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '91': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '92': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '93': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '94': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '95': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '96': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '97': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '98': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '99': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '100': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '101': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '102': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '103': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '104': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '105': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '106': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '107': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '108': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '109': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '110': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '111': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '112': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
        '113': {
          family: 'Geist',
          weight: undefined,
          size: undefined,
          lineHeight: NaN,
        },
      },
      title: {
        lg: {
          family: 'Geist',
          weight: 600,
          size: 17,
          lineHeight: 1.24,
        },
        md: {
          family: 'Geist',
          weight: 600,
          size: 14,
          lineHeight: 1.28,
        },
        sm: {
          family: 'Geist',
          weight: 600,
          size: 12,
          lineHeight: 1.28,
        },
      },
      body: {
        lg: {
          family: 'Geist',
          weight: 400,
          size: 14,
          lineHeight: 1.48,
        },
        md: {
          family: 'Geist',
          weight: 400,
          size: 12,
          lineHeight: 1.52,
        },
        sm: {
          family: 'Geist',
          weight: 400,
          size: 10.5,
          lineHeight: 1.48,
        },
      },
      label: {
        lg: {
          family: 'Geist',
          weight: 500,
          size: 11,
          lineHeight: 1.0,
        },
        md: {
          family: 'Geist',
          weight: 600,
          size: 9.5,
          lineHeight: 1.0,
        },
        sm: {
          family: 'Geist',
          weight: 600,
          size: 8.5,
          lineHeight: 1.0,
        },
      },
    },
    instrument: {
      $comment: {
        family: 'Geist',
        weight: undefined,
        size: undefined,
        lineHeight: NaN,
      },
      lg: {
        family: 'JetBrainsMono',
        weight: 500,
        size: 18,
        lineHeight: 1.12,
      },
      md: {
        family: 'JetBrainsMono',
        weight: 500,
        size: 13,
        lineHeight: 1.2,
      },
      sm: {
        family: 'JetBrainsMono',
        weight: 500,
        size: 10,
        lineHeight: 1.2,
      },
      xs: {
        family: 'JetBrainsMono',
        weight: 500,
        size: 8.5,
        lineHeight: 1.0,
      },
    },
  },
  icon: {
    name: [
      'bike',
      'bookmark',
      'bookmarkFill',
      'chevL',
      'chevR',
      'clock',
      'close',
      'collapse',
      'compass',
      'edit',
      'expand',
      'heart',
      'heartFill',
      'layers',
      'map',
      'menu',
      'pin',
      'plus',
      'rain',
      'route',
      'send',
      'share',
      'sliders',
      'sparkle',
      'star',
      'starFill',
      'storm',
      'sun',
      'therm',
      'trash',
      'wind',
    ],
  },
} as const

export type Tokens = typeof tokens
