const { test } = require('node:test')
const assert = require('node:assert/strict')
const { formatKotlin, colorArgb } = require('../kotlin-tokens.js')

test('colorArgb produces 0xAARRGGBB int from hex', () => {
  assert.equal(colorArgb('#B87333'), 0xffb87333)
})

test('colorArgb produces 0xAARRGGBB int from rgba', () => {
  assert.equal(colorArgb('rgba(255,255,255,0.5)'), 0x80ffffff)
})

test('formatKotlin emits nested object namespace with Color literal', () => {
  const dict = {
    tokens: {
      semantic: {
        color: {
          light: {
            primary: {
              default: { $type: 'color', $value: '#B87333' },
            },
          },
        },
        space: {
          md: { $type: 'dimension', $value: 12 },
        },
      },
    },
  }
  const out = formatKotlin(dict)
  assert.match(out, /\/\/ @generated by tokens\/scripts\/build\.js — do not edit/)
  assert.match(out, /package com\.laneshadow\.theme\.generated/)
  assert.match(out, /import androidx\.compose\.ui\.graphics\.Color/)
  assert.match(out, /import androidx\.compose\.ui\.unit\.dp/)
  assert.match(out, /public object Tokens \{/)
  assert.match(out, /public object Semantic \{/)
  assert.match(out, /public object Color \{/)
  assert.match(out, /public object Light \{/)
  assert.match(out, /public object Primary \{/)
  assert.match(
    out,
    /public val `default`: androidx\.compose\.ui\.graphics\.Color = androidx\.compose\.ui\.graphics\.Color\(0xFFB87333\)/,
  )
  assert.match(out, /public val md: androidx\.compose\.ui\.unit\.Dp = 12\.dp/)
})
