const { test } = require('node:test')
const assert = require('node:assert/strict')
const { formatSwift, parseColor } = require('../swift-tokens.js')

test('parseColor handles hex without alpha', () => {
  assert.deepEqual(parseColor('#B87333'), {
    red: 0xb8 / 255,
    green: 0x73 / 255,
    blue: 0x33 / 255,
    alpha: 1,
  })
})

test('parseColor handles 8-char hex with alpha', () => {
  const c = parseColor('#B87333FF')
  assert.equal(c.alpha, 1)
})

test('parseColor handles rgba', () => {
  const c = parseColor('rgba(255,255,255,0.92)')
  assert.equal(c.red, 1)
  assert.equal(c.alpha, 0.92)
})

test('formatSwift emits nested enum namespace with Color literal', () => {
  const dict = {
    tokens: {
      semantic: {
        color: {
          light: {
            primary: {
              default: { $type: 'color', $value: '#B87333' },
            },
          },
        },
        space: {
          md: { $type: 'dimension', $value: 12 },
        },
      },
    },
  }
  const out = formatSwift(dict)
  assert.match(out, /\/\/ @generated by tokens\/scripts\/build\.js — do not edit/)
  assert.match(out, /import SwiftUI/)
  assert.match(out, /public enum Tokens \{/)
  assert.match(out, /public enum Semantic \{/)
  assert.match(out, /public enum Color \{/)
  assert.match(out, /public enum Light \{/)
  assert.match(out, /public enum Primary \{/)
  assert.match(
    out,
    /public static let `default`: SwiftUI\.Color = SwiftUI\.Color\(red: 0\.7215686274509804, green: 0\.45098039215686275, blue: 0\.2/,
  )
  assert.match(out, /public enum Space \{/)
  assert.match(out, /public static let md: CGFloat = 12/)
})
