const { test } = require('node:test')
const assert = require('node:assert/strict')
const { formatTypeScript } = require('../typescript-tokens.js')

const sampleDict = {
  tokens: {
    semantic: {
      color: {
        light: {
          primary: {
            default: { $type: 'color', $value: '#B87333' },
            hover: { $type: 'color', $value: '#C58545' },
          },
        },
      },
      space: {
        md: { $type: 'dimension', $value: 12 },
      },
    },
  },
}

test('formatTypeScript emits as-const tokens object', () => {
  const out = formatTypeScript(sampleDict)
  assert.match(out, /\/\/ @generated by tokens\/scripts\/build\.js — do not edit/)
  assert.match(out, /export const tokens = \{/)
  assert.match(out, /primary: \{[\s\S]*default: ['"]#B87333['"]/)
  assert.match(out, /md: 12/)
  assert.match(out, /\} as const/)
})

test('formatTypeScript handles rgba color values', () => {
  const dict = {
    tokens: {
      semantic: {
        color: {
          dark: {
            onSurface: { default: { $type: 'color', $value: 'rgba(255,255,255,0.92)' } },
          },
        },
      },
    },
  }
  const out = formatTypeScript(dict)
  assert.match(out, /default: ['"]rgba\(255,255,255,0\.92\)['"]/)
})
