/**
 * Integration test for DATA-011 AC-3: discoverCuratedRoutes returns the real line
 * when present, falls back to centroid when absent.
 *
 * This test verifies the `buildCuratedMapGeometry` function by exercising it
 * against REAL geometry persisted on live Convex dev. No synthetic fallbacks —
 * the generated route MUST have real geometry in the side table (generated by
 * the actual `generateForRoute` action), and the unresolved route MUST have
 * none (confirmed by querying the side table).
 *
 * AC-3: GIVEN one generated + one unresolved route WHEN discoverCuratedRoutes
 * builds options THEN the generated route's overviewGeometry decodes to >1 coord
 * and the unresolved falls back to centroid; neither crashes.
 *
 * Run: pnpm test convex/actions/agent/__tests__/discoverCuratedRoutesGeometry.integration.test.ts
 */

import { execSync } from 'node:child_process'
import polyline from '@mapbox/polyline'
import { describe, expect, it } from 'vitest'
import {
  buildCuratedMapGeometry,
  encodeCentroidToPolyline,
} from '../../agent/tools/discoverCuratedRoutes'

// ---------------------------------------------------------------------------
// Convex CLI helpers
// ---------------------------------------------------------------------------

/** Run a Convex internal function via `npx convex run` and parse JSON result. */
function convexRun(fnPath: string, args: Record<string, unknown>): unknown {
  const argsJson = JSON.stringify(args).replace(/'/g, "'\"'\"'")
  const cmd = `npx convex run ${fnPath} '${argsJson}'`
  const result = execSync(cmd, {
    encoding: 'utf-8',
    timeout: 120_000, // generateForRoute calls real Nominatim + Google Routes
    stdio: ['ignore', 'pipe', 'pipe'],
  })
  const lines = result
    .split('\n')
    .filter((l) => !l.startsWith('npm warn'))
    .join('\n')
    .trim()
  if (!lines) return null
  return JSON.parse(lines)
}

/** Fetch generated geometry for routes from the side table. */
function getGeometryForRoutes(routeIds: string[]) {
  return convexRun('curatedGeometry:getGeometryForRoutes', { routeIds }) as Array<{
    routeId: string
    format: 'polyline' | 'multipolyline'
    encoding: string
    precision: number
    value: string | null
    segments: string[] | null
  }> | null
}

/** Read a route's current state from Convex. */
function getRouteState(routeId: string) {
  return convexRun('curatedGeometry:getRouteForGeneration', { routeId }) as {
    routeId: string
    name: string
    state: string
    geometryStatus: 'generated' | 'unresolved' | 'failed' | null
    id: string
  } | null
}

/** Clear a route's geometry (so it can be re-processed). Returns void. */
function clearRouteGeometry(id: string): void {
  convexRun('curatedGeometry:clearGeometry', { id })
}

/** Generate geometry for a route via the real action. */
function generateForRoute(routeId: string) {
  return convexRun('actions/curatedGeometry:generateForRoute', { routeId }) as {
    routeId: string
    name: string
    state: string
    geometryStatus: 'generated' | 'unresolved' | 'failed'
    coordCount?: number
    error?: string
  }
}

// ---------------------------------------------------------------------------
// Fixtures — curated route docs (as returned by listCuratedRoutes)
// ---------------------------------------------------------------------------

const GENERATED_ROUTE = {
  routeId: 'motorcycleroads:going-to-the-sun-road',
  name: 'Going-To-The-Sun Road',
  centroidLat: 48.6,
  centroidLng: -113.8,
  boundsNeLat: 48.8,
  boundsNeLng: -113.0,
  boundsSwLat: 48.4,
  boundsSwLng: -114.2,
  geometryStatus: 'generated' as const,
}

/**
 * A known unresolvable route: "MO-14 - Ava to Sparta" in Missouri.
 * Generic Missouri state highway segment names do NOT resolve in Nominatim.
 * The centroidLat/Lng values are from the catalog entry.
 */
const UNRESOLVED_ROUTE = {
  routeId: 'motorcycleroads:mo-14-ava-to-sparta',
  name: 'MO-14 - Ava to Sparta',
  centroidLat: 36.95,
  centroidLng: -92.92,
  boundsNeLat: 37.05,
  boundsNeLng: -92.8,
  boundsSwLat: 36.85,
  boundsSwLng: -93.05,
  geometryStatus: 'unresolved' as const,
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe('DATA-011 AC-3: discoverCuratedRoutes geometry reader', () => {
  /**
   * AC-3: the generated route's overviewGeometry decodes to > 1 coordinate.
   *
   * Ensures the route has real geometry in the Convex side table by running
   * generateForRoute (if not already generated), then exercises
   * buildCuratedMapGeometry with the REAL persisted geometry.
   * No synthetic fallback — if no real geometry exists the test fails.
   */
  it('returnsRealLineWhenPresentElseCentroidFallback: live geometry from Convex', () => {
    // Ensure the route has real generated geometry (generate if needed)
    const routeState = getRouteState(GENERATED_ROUTE.routeId)
    expect(routeState).not.toBeNull()
    if (routeState!.geometryStatus !== 'generated') {
      // Clear and regenerate to ensure real geometry exists
      if (routeState!.geometryStatus !== null) {
        clearRouteGeometry(routeState!.id)
      }
      const genResult = generateForRoute(GENERATED_ROUTE.routeId)
      expect(genResult.geometryStatus).toBe('generated')
    }

    // Fetch the real geometry from the side table — MUST exist (no synthetic fallback)
    const geometryRows = getGeometryForRoutes([GENERATED_ROUTE.routeId])
    expect(geometryRows).not.toBeNull()
    expect(geometryRows!.length).toBeGreaterThan(0)

    const geoRow = geometryRows![0]
    expect(geoRow.value).toBeTruthy()

    const g = {
      format: geoRow.format,
      precision: geoRow.precision,
      value: geoRow.value,
      segments: geoRow.segments,
    }

    const result = buildCuratedMapGeometry(GENERATED_ROUTE, g)

    // The overviewGeometry should be a polyline that decodes to >1 coordinate
    const decoded = polyline.decode(
      result.overviewGeometry.value,
      result.overviewGeometry.precision,
    ) as [number, number][]
    expect(decoded.length).toBeGreaterThan(1)

    // Bounds should be derived from the actual geometry
    expect(result.bounds.north).toBeGreaterThan(result.bounds.south)
    expect(result.bounds.east).toBeGreaterThan(result.bounds.west)

    // Verify coordinates are in the route's geographic area (Montana)
    for (const [lat, lng] of decoded) {
      expect(lat).toBeGreaterThan(47)
      expect(lat).toBeLessThan(49)
      expect(lng).toBeGreaterThan(-115)
      expect(lng).toBeLessThan(-112)
    }
  }, 180_000) // extended timeout for real Nominatim + Google Routes API calls

  /**
   * AC-3: the unresolved route falls back to the centroid encode (current behavior).
   * Ensures the route has NO geometry by running generateForRoute (which will mark
   * it unresolved) and then verifies buildCuratedMapGeometry falls back correctly.
   * No synthetic data — the unresolved state is confirmed against real Convex.
   */
  it('returnsRealLineWhenPresentElseCentroidFallback: unresolved route falls back to centroid', () => {
    // Ensure the route is in unresolved state (generate to confirm it's unresolvable)
    const routeState = getRouteState(UNRESOLVED_ROUTE.routeId)
    expect(routeState).not.toBeNull()
    if (routeState!.geometryStatus !== 'unresolved' && routeState!.geometryStatus !== 'failed') {
      // Clear any existing state and regenerate to confirm unresolvable
      if (routeState!.geometryStatus !== null) {
        clearRouteGeometry(routeState!.id)
      }
      const genResult = generateForRoute(UNRESOLVED_ROUTE.routeId)
      expect(['unresolved', 'failed']).toContain(genResult.geometryStatus)
    }

    // Fetch geometry for the unresolved route — should return empty (no geometry)
    const geometryRows = getGeometryForRoutes([UNRESOLVED_ROUTE.routeId])

    // No geometry should be present for the unresolved route
    const g = geometryRows && geometryRows.length > 0 ? geometryRows[0] : null
    expect(g).toBeNull()

    const result = buildCuratedMapGeometry(UNRESOLVED_ROUTE, null)

    // overviewGeometry should be the centroid single-point encode
    const decoded = polyline.decode(
      result.overviewGeometry.value,
      result.overviewGeometry.precision,
    ) as [number, number][]
    expect(decoded.length).toBe(1) // single point (centroid fallback)
    expect(decoded[0][0]).toBeCloseTo(UNRESOLVED_ROUTE.centroidLat, 3)
    expect(decoded[0][1]).toBeCloseTo(UNRESOLVED_ROUTE.centroidLng, 3)

    // Bounds should be the centroid ±0.5° fallback
    expect(result.bounds.north).toBeCloseTo(UNRESOLVED_ROUTE.centroidLat + 0.5, 3)
    expect(result.bounds.south).toBeCloseTo(UNRESOLVED_ROUTE.centroidLat - 0.5, 3)
  }, 180_000)

  /**
   * AC-3: neither path crashes — the generated route works, the unresolved
   * route works, and the function handles both gracefully.
   */
  it('returnsRealLineWhenPresentElseCentroidFallback: neither path crashes', () => {
    // Generated route with polyline geometry
    const polylineGeometry = {
      format: 'polyline' as const,
      encoding: 'google_encoded_polyline',
      precision: 5,
      value: polyline.encode([
        [48.5, -114.0],
        [48.6, -113.5],
        [48.7, -113.2],
      ] as [number, number][]),
    }
    expect(() => buildCuratedMapGeometry(GENERATED_ROUTE, polylineGeometry)).not.toThrow()

    // Unresolved route without geometry
    expect(() => buildCuratedMapGeometry(UNRESOLVED_ROUTE, null)).not.toThrow()

    // Undefined geometry (edge case)
    expect(() => buildCuratedMapGeometry(UNRESOLVED_ROUTE, undefined)).not.toThrow()
  })

  /**
   * Edge case: geometry with value but decodes to <2 points should fall back
   * to centroid (defensive — a single-point polyline is not a real line).
   */
  it('falls back to centroid when geometry value decodes to <2 points', () => {
    const badGeometry = {
      format: 'polyline' as const,
      encoding: 'google_encoded_polyline',
      precision: 5,
      value: polyline.encode([[48.6, -113.8]] as [number, number][]), // single-point
    }

    const result = buildCuratedMapGeometry(GENERATED_ROUTE, badGeometry)

    // Falls back to centroid because decoded points < 2
    const decoded = polyline.decode(
      result.overviewGeometry.value,
      result.overviewGeometry.precision,
    ) as [number, number][]
    expect(decoded.length).toBe(1) // centroid fallback
  })
})

describe('encodeCentroidToPolyline', () => {
  it('encodes a single centroid point as a polyline', () => {
    const encoded = encodeCentroidToPolyline(48.6, -113.8)
    const decoded = polyline.decode(encoded, 5) as [number, number][]

    expect(decoded.length).toBe(1)
    expect(decoded[0][0]).toBeCloseTo(48.6, 3)
    expect(decoded[0][1]).toBeCloseTo(-113.8, 3)
  })
})
