/**
 * Variance report JSON schema for screenshot diffing.
 *
 * This schema defines the structure of variance reports generated by the UI diff harness.
 * Reports are consumed by CI/CD pipelines and provide machine-readable pass/fail status.
 *
 * Per 08d-component-parity-spec, pixel-perfect matching uses ±1px tolerance for anti-aliasing.
 */

export interface PixelVariance {
  /** Total pixels in the image */
  totalPixels: number
  /** Number of pixels that differ */
  differentPixels: number
  /** Percentage of pixels that differ (0-100) */
  percentageDiff: number
  /** Maximum difference in any RGB channel (0-255) */
  maxChannelDiff: number
}

export interface ComponentVariance {
  /** Component name (e.g., "ThemeButton", "RouteCard") */
  component: string
  /** Platform: "rn" | "android" | "ios" */
  platform: string
  /** Baseline screenshot path */
  baselinePath: string
  /** Current screenshot path */
  currentPath: string
  /** Diff output path (highlighted differences) */
  diffPath: string
  /** Pixel-level variance metrics */
  variance: PixelVariance
  /** Pass/fail status based on tolerance threshold */
  status: 'pass' | 'fail' | 'warn'
  /** Human-readable explanation */
  message: string
}

export interface PlatformReport {
  /** Platform name */
  platform: 'rn' | 'android' | 'ios'
  /** Number of components tested */
  totalComponents: number
  /** Number of components that passed */
  passed: number
  /** Number of components that failed */
  failed: number
  /** Number of components with warnings */
  warned: number
  /** Per-component variance details */
  components: ComponentVariance[]
}

export interface VarianceReport {
  /** Report schema version */
  schemaVersion: '1.0.0'
  /** ISO timestamp of report generation */
  timestamp: string
  /** Git commit SHA being tested */
  commitSha: string
  /** Git branch being tested */
  branch: string
  /** Pixel tolerance threshold used for comparison */
  tolerance: number
  /** Overall pass/fail status */
  status: 'pass' | 'fail'
  /** Per-platform reports */
  platforms: PlatformReport[]
  /** Summary statistics */
  summary: {
    /** Total components across all platforms */
    totalComponents: number
    /** Total passed across all platforms */
    totalPassed: number
    /** Total failed across all platforms */
    totalFailed: number
    /** Total warned across all platforms */
    totalWarned: number
  }
}

/**
 * Validates that an object conforms to the VarianceReport schema.
 */
export function validateVarianceReport(report: unknown): report is VarianceReport {
  if (typeof report !== 'object' || report === null) {
    return false
  }

  const r = report as Partial<VarianceReport>

  // Check required top-level fields
  if (
    r.schemaVersion !== '1.0.0' ||
    typeof r.timestamp !== 'string' ||
    typeof r.commitSha !== 'string' ||
    typeof r.branch !== 'string' ||
    typeof r.tolerance !== 'number' ||
    (r.status !== 'pass' && r.status !== 'fail') ||
    !Array.isArray(r.platforms) ||
    typeof r.summary !== 'object' ||
    r.summary === null
  ) {
    return false
  }

  // Check platforms array structure
  for (const platform of r.platforms) {
    if (
      (platform.platform !== 'rn' &&
        platform.platform !== 'android' &&
        platform.platform !== 'ios') ||
      typeof platform.totalComponents !== 'number' ||
      typeof platform.passed !== 'number' ||
      typeof platform.failed !== 'number' ||
      typeof platform.warned !== 'number' ||
      !Array.isArray(platform.components)
    ) {
      return false
    }

    // Check component variance structure
    for (const component of platform.components) {
      if (
        typeof component.component !== 'string' ||
        typeof component.platform !== 'string' ||
        typeof component.baselinePath !== 'string' ||
        typeof component.currentPath !== 'string' ||
        typeof component.diffPath !== 'string' ||
        typeof component.variance !== 'object' ||
        component.variance === null ||
        (component.status !== 'pass' &&
          component.status !== 'fail' &&
          component.status !== 'warn') ||
        typeof component.message !== 'string'
      ) {
        return false
      }

      const v = component.variance
      if (
        typeof v.totalPixels !== 'number' ||
        typeof v.differentPixels !== 'number' ||
        typeof v.percentageDiff !== 'number' ||
        typeof v.maxChannelDiff !== 'number'
      ) {
        return false
      }
    }
  }

  // Check summary structure
  const s = r.summary
  if (
    typeof s.totalComponents !== 'number' ||
    typeof s.totalPassed !== 'number' ||
    typeof s.totalFailed !== 'number' ||
    typeof s.totalWarned !== 'number'
  ) {
    return false
  }

  return true
}

/**
 * Creates an empty variance report template.
 */
export function createEmptyReport(
  commitSha: string,
  branch: string,
  tolerance: number = 1,
): VarianceReport {
  return {
    schemaVersion: '1.0.0',
    timestamp: new Date().toISOString(),
    commitSha,
    branch,
    tolerance,
    status: 'pass',
    platforms: [],
    summary: {
      totalComponents: 0,
      totalPassed: 0,
      totalFailed: 0,
      totalWarned: 0,
    },
  }
}

/**
 * Adds a platform report to the variance report.
 */
export function addPlatformReport(
  report: VarianceReport,
  platformReport: PlatformReport,
): VarianceReport {
  const updated = {
    ...report,
    platforms: [...report.platforms, platformReport],
  }

  // Recalculate summary
  updated.summary = {
    totalComponents: report.summary.totalComponents + platformReport.totalComponents,
    totalPassed: report.summary.totalPassed + platformReport.passed,
    totalFailed: report.summary.totalFailed + platformReport.failed,
    totalWarned: report.summary.totalWarned + platformReport.warned,
  }

  // Update overall status if any platform failed
  if (platformReport.failed > 0) {
    updated.status = 'fail'
  }

  return updated
}
