const { toPlain, toKotlinLiteral, kotlinIdentifier } = require('./_shared')

function renderKotlinTree(key, node, indent) {
  const i = '  '.repeat(indent)

  if (node && typeof node === 'object' && !Array.isArray(node)) {
    const entries = Object.entries(node)
    const isLeaf =
      entries.length > 0 &&
      entries.every(([, v]) => v === null || typeof v !== 'object' || Array.isArray(v))

    if (isLeaf) {
      return `${i}val ${kotlinIdentifier(key)} = ${toKotlinLiteral(node)}`
    }

    const header = `${i}object ${kotlinIdentifier(key)} {`
    const body = entries
      .map(([childKey, childNode]) => renderKotlinTree(childKey, childNode, indent + 1))
      .join('\n')
    const footer = `${i}}`
    return `${header}\n${body}\n${footer}`
  }

  return `${i}val ${kotlinIdentifier(key)} = ${toKotlinLiteral(node)}`
}

module.exports = ({ dictionary }) => {
  const plain = toPlain(dictionary.tokens)
  const body = Object.entries(plain)
    .map(([k, v]) => renderKotlinTree(k, v, 1))
    .join('\n')

  return `@file:Suppress("MemberVisibilityCanBePrivate", "unused")
// @generated by Style Dictionary (UI-001).
// Source: tokens/**
// Output: tokens/generated/kotlin/LaneShadowTokens.kt

package com.laneshadow.tokens.generated

object LaneShadowTokens {
${body}
}
`
}
