const { toPlain, toSwiftLiteral, swiftIdentifier } = require('./_shared')

function renderSwiftTree(key, node, indent) {
  const i = '  '.repeat(indent)

  if (node && typeof node === 'object' && !Array.isArray(node)) {
    const entries = Object.entries(node)
    // Leaf object literal: still render as a value (Dictionary) to avoid guessing structs.
    // We keep this generic; platform wrappers can add typed accessors later.
    const isLeaf =
      entries.length > 0 &&
      entries.every(([, v]) => v === null || typeof v !== 'object' || Array.isArray(v))

    if (isLeaf) {
      return `${i}public static let ${swiftIdentifier(key)} = ${toSwiftLiteral(node)}`
    }

    const header = `${i}public enum ${swiftIdentifier(key)} {`
    const body = entries
      .map(([childKey, childNode]) => renderSwiftTree(childKey, childNode, indent + 1))
      .join('\n')
    const footer = `${i}}`
    return `${header}\n${body}\n${footer}`
  }

  return `${i}public static let ${swiftIdentifier(key)} = ${toSwiftLiteral(node)}`
}

module.exports = ({ dictionary }) => {
  const plain = toPlain(dictionary.tokens)
  const body = Object.entries(plain)
    .map(([k, v]) => renderSwiftTree(k, v, 1))
    .join('\n')

  return `// swiftlint:disable all
// @generated by Style Dictionary (UI-001).
// Source: tokens/**
// Output: tokens/generated/swift/LaneShadowTokens.swift

import Foundation

public enum LaneShadowTokens {
${body}
}
`
}
