const { toPlain, toTypescriptLiteral } = require('./_shared')

module.exports = ({ dictionary }) => {
  const plain = toPlain(dictionary.tokens)
  return `/* eslint-disable */
/**
 * @generated by Style Dictionary (UI-001).
 * Source: tokens/**
 * Output: react-native/styles/generated/tokens.ts
 */

export const tokens = ${toTypescriptLiteral(plain)} as const;
export type Tokens = typeof tokens;
`
}
