const HEADER = `// @generated by tokens/scripts/build.js — do not edit
//
// Source: tokens/semantic/semantic.tokens.json

@file:Suppress("MagicNumber", "TopLevelPropertyNaming", "ObjectPropertyNaming")
package com.laneshadow.theme.generated

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontWeight

`

function pascalCase(s) {
  if (/^\d/.test(s)) return `_${s.replace(/[^a-zA-Z0-9]/g, '_')}`
  return s.replace(/(^|[-_ ])(.)/g, (_, __, c) => c.toUpperCase())
}

function camelCase(s) {
  if (/^\d/.test(s)) return `_${s.replace(/[^a-zA-Z0-9]/g, '_')}`
  const parts = s.split(/[-_ ]/)
  return (
    parts[0] +
    parts
      .slice(1)
      .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
      .join('')
  )
}

const KOTLIN_HARD_KEYWORDS = new Set([
  'as',
  'break',
  'class',
  'continue',
  'do',
  'else',
  'false',
  'for',
  'fun',
  'if',
  'in',
  'interface',
  'is',
  'null',
  'object',
  'package',
  'return',
  'super',
  'this',
  'throw',
  'true',
  'try',
  'typealias',
  'val',
  'var',
  'when',
  'while',
  'default',
])

function escapeIdent(name) {
  return KOTLIN_HARD_KEYWORDS.has(name) ? `\`${name}\`` : name
}

function parseColorArgb(value) {
  if (typeof value !== 'string') {
    throw new Error(`color value must be string: ${JSON.stringify(value)}`)
  }
  const trimmed = value.trim()
  if (trimmed.startsWith('#')) {
    const hex = trimmed.slice(1)
    const expand = (h) =>
      h.length === 3
        ? h
            .split('')
            .map((c) => c + c)
            .join('')
        : h
    const norm = expand(hex)
    if (norm.length === 6) {
      return (0xff000000 | Number.parseInt(norm, 16)) >>> 0
    }
    if (norm.length === 8) {
      const rgb = Number.parseInt(norm.slice(0, 6), 16)
      const a = Number.parseInt(norm.slice(6, 8), 16)
      return ((a << 24) | rgb) >>> 0
    }
  }
  const m = trimmed.match(
    /^rgba?\(\s*(\d+(?:\.\d+)?)\s*,\s*(\d+(?:\.\d+)?)\s*,\s*(\d+(?:\.\d+)?)\s*(?:,\s*(\d+(?:\.\d+)?)\s*)?\)$/,
  )
  if (m) {
    const r = Math.round(Number.parseFloat(m[1]))
    const g = Math.round(Number.parseFloat(m[2]))
    const b = Math.round(Number.parseFloat(m[3]))
    const a = m[4] !== undefined ? Math.round(Number.parseFloat(m[4]) * 255) : 255
    return ((a << 24) | (r << 16) | (g << 8) | b) >>> 0
  }
  throw new Error(`Unsupported color value: ${value}`)
}

const colorArgb = parseColorArgb

function emitColor(value) {
  const argb = parseColorArgb(value)
  const hex = argb.toString(16).toUpperCase().padStart(8, '0')
  return `androidx.compose.ui.graphics.Color(0x${hex})`
}

function emitTypography(value) {
  const weight = value.fontWeight
  const weightExpr =
    weight === '100'
      ? 'FontWeight.Thin'
      : weight === '200'
        ? 'FontWeight.ExtraLight'
        : weight === '300'
          ? 'FontWeight.Light'
          : weight === '400' || weight === 'normal'
            ? 'FontWeight.Normal'
            : weight === '500'
              ? 'FontWeight.Medium'
              : weight === '600'
                ? 'FontWeight.SemiBold'
                : weight === '700' || weight === 'bold'
                  ? 'FontWeight.Bold'
                  : weight === '800'
                    ? 'FontWeight.ExtraBold'
                    : weight === '900'
                      ? 'FontWeight.Black'
                      : 'FontWeight.Normal'
  return `TextStyle(fontSize = ${value.fontSize}.sp, lineHeight = ${value.lineHeight}.sp, fontWeight = ${weightExpr})`
}

function emitElevation(value) {
  return `LaneShadowElevation(elevation = ${value.elevation}.dp, offsetX = ${value.shadowOffset?.width ?? 0}.dp, offsetY = ${value.shadowOffset?.height ?? 0}.dp, opacity = ${value.shadowOpacity}f, radius = ${value.shadowRadius}.dp)`
}

function leafValue(node) {
  const t = node.$type
  const v = node.$value
  if (t === 'color') return { type: 'androidx.compose.ui.graphics.Color', expr: emitColor(v) }
  if (t === 'dimension') return { type: 'androidx.compose.ui.unit.Dp', expr: `${v}.dp` }
  if (t === 'integer') return { type: 'Int', expr: String(v) }
  if (t === 'number') return { type: 'Double', expr: `${v}` }
  if (t === 'opacity') return { type: 'Float', expr: `${v}f` }
  if (t === 'fontWeight') return { type: 'String', expr: JSON.stringify(v) }
  if (t === 'string' && (v === 'transparent' || v === 'clear')) {
    return {
      type: 'androidx.compose.ui.graphics.Color',
      expr: 'androidx.compose.ui.graphics.Color.Transparent',
    }
  }
  if (t === 'typography')
    return { type: 'androidx.compose.ui.text.TextStyle', expr: emitTypography(v) }
  if (t === 'shadow' || t === 'elevation')
    return { type: 'com.laneshadow.theme.LaneShadowElevation', expr: emitElevation(v) }
  if (t === 'cubicBezier') return { type: 'List<Double>', expr: `listOf(${v.join(', ')})` }
  if (t === 'duration') return { type: 'Int', expr: String(v) }
  if (Array.isArray(v)) {
    // Force every element to Double so Kotlin's type inference doesn't mix Int/Double.
    const doubles = v.map((n) => (Number.isInteger(n) ? `${n}.0` : String(n)))
    return { type: 'List<Double>', expr: `listOf(${doubles.join(', ')})` }
  }
  return { type: 'String', expr: JSON.stringify(v) }
}

function isLeaf(node) {
  return node && typeof node === 'object' && '$value' in node
}

function emitNamespace(name, node, indent) {
  const lines = [`${indent}public object ${pascalCase(name)} {`]
  for (const [key, child] of Object.entries(node)) {
    if (isLeaf(child)) {
      const { type, expr } = leafValue(child)
      lines.push(`${indent}  public val ${escapeIdent(camelCase(key))}: ${type} = ${expr}`)
    } else {
      lines.push(emitNamespace(key, child, `${indent}  `))
    }
  }
  lines.push(`${indent}}`)
  return lines.join('\n')
}

function formatKotlin(dict) {
  const root = dict.tokens || dict
  return `${HEADER}${emitNamespace('Tokens', root, '')}\n`
}

module.exports = { formatKotlin, colorArgb }
