const HEADER = `// @generated by tokens/scripts/build.js — do not edit
//
// Source: tokens/semantic/semantic.tokens.json

import SwiftUI
import CoreGraphics

`

function pascalCase(s) {
  if (/^\d/.test(s)) return `_${s.replace(/[^a-zA-Z0-9]/g, '_')}`
  return s.replace(/(^|[-_ ])(.)/g, (_, __, c) => c.toUpperCase())
}

function camelCase(s) {
  if (/^\d/.test(s)) return `_${s.replace(/[^a-zA-Z0-9]/g, '_')}`
  const parts = s.split(/[-_ ]/)
  return (
    parts[0] +
    parts
      .slice(1)
      .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
      .join('')
  )
}

const SWIFT_RESERVED = new Set([
  'default',
  'class',
  'struct',
  'enum',
  'func',
  'let',
  'var',
  'if',
  'else',
  'for',
  'while',
  'repeat',
  'switch',
  'case',
  'break',
  'continue',
  'return',
  'public',
  'private',
  'internal',
  'fileprivate',
  'open',
  'static',
  'true',
  'false',
  'Type',
])

function escapeIdent(name) {
  return SWIFT_RESERVED.has(name) ? `\`${name}\`` : name
}

function parseColor(value) {
  if (typeof value !== 'string') {
    throw new Error(`color value must be string: ${JSON.stringify(value)}`)
  }
  const trimmed = value.trim()
  if (trimmed.startsWith('#')) {
    const hex = trimmed.slice(1)
    const expand = (h) =>
      h.length === 3
        ? h
            .split('')
            .map((c) => c + c)
            .join('')
        : h
    const norm = expand(hex)
    if (norm.length === 6) {
      return {
        red: Number.parseInt(norm.slice(0, 2), 16) / 255,
        green: Number.parseInt(norm.slice(2, 4), 16) / 255,
        blue: Number.parseInt(norm.slice(4, 6), 16) / 255,
        alpha: 1,
      }
    }
    if (norm.length === 8) {
      return {
        red: Number.parseInt(norm.slice(0, 2), 16) / 255,
        green: Number.parseInt(norm.slice(2, 4), 16) / 255,
        blue: Number.parseInt(norm.slice(4, 6), 16) / 255,
        alpha: Number.parseInt(norm.slice(6, 8), 16) / 255,
      }
    }
  }
  const m = trimmed.match(
    /^rgba?\(\s*(\d+(?:\.\d+)?)\s*,\s*(\d+(?:\.\d+)?)\s*,\s*(\d+(?:\.\d+)?)\s*(?:,\s*(\d+(?:\.\d+)?)\s*)?\)$/,
  )
  if (m) {
    return {
      red: Number.parseFloat(m[1]) / 255,
      green: Number.parseFloat(m[2]) / 255,
      blue: Number.parseFloat(m[3]) / 255,
      alpha: m[4] !== undefined ? Number.parseFloat(m[4]) : 1,
    }
  }
  throw new Error(`Unsupported color value: ${value}`)
}

function emitColor(value) {
  const c = parseColor(value)
  return `SwiftUI.Color(red: ${c.red}, green: ${c.green}, blue: ${c.blue}, opacity: ${c.alpha})`
}

function emitTypography(value) {
  const weight = value.fontWeight
  const weightExpr =
    weight === '100'
      ? '.ultraLight'
      : weight === '200'
        ? '.thin'
        : weight === '300'
          ? '.light'
          : weight === '400' || weight === 'normal'
            ? '.regular'
            : weight === '500'
              ? '.medium'
              : weight === '600'
                ? '.semibold'
                : weight === '700' || weight === 'bold'
                  ? '.bold'
                  : weight === '800'
                    ? '.heavy'
                    : weight === '900'
                      ? '.black'
                      : '.regular'
  return `LaneShadowTypographyStyle(fontSize: ${value.fontSize}, lineHeight: ${value.lineHeight}, fontWeight: ${weightExpr})`
}

function emitElevation(value) {
  const off = value.shadowOffset || { width: 0, height: 0 }
  const color =
    value.shadowColor === 'transparent' ? 'SwiftUI.Color.clear' : emitColor(value.shadowColor)
  return `LaneShadowElevation(shadowColor: ${color}, offsetX: ${off.width}, offsetY: ${off.height}, opacity: ${value.shadowOpacity}, radius: ${value.shadowRadius}, elevation: ${value.elevation})`
}

function emitMotionEasing(value) {
  if (Array.isArray(value)) {
    return `LaneShadowEasing(c1x: ${value[0]}, c1y: ${value[1]}, c2x: ${value[2]}, c2y: ${value[3]})`
  }
  return JSON.stringify(value)
}

function leafValue(node) {
  const t = node.$type
  const v = node.$value
  if (t === 'color') return { type: 'SwiftUI.Color', expr: emitColor(v) }
  if (t === 'dimension') return { type: 'CGFloat', expr: String(v) }
  if (t === 'integer') return { type: 'Int', expr: String(v) }
  if (t === 'number') return { type: 'Double', expr: String(v) }
  if (t === 'opacity') return { type: 'Double', expr: String(v) }
  if (t === 'fontWeight') return { type: 'String', expr: JSON.stringify(v) }
  if (t === 'string' && (v === 'transparent' || v === 'clear')) {
    return { type: 'SwiftUI.Color', expr: 'SwiftUI.Color.clear' }
  }
  if (t === 'typography') return { type: 'LaneShadowTypographyStyle', expr: emitTypography(v) }
  if (t === 'shadow' || t === 'elevation')
    return { type: 'LaneShadowElevation', expr: emitElevation(v) }
  if (t === 'cubicBezier') return { type: 'LaneShadowEasing', expr: emitMotionEasing(v) }
  if (t === 'duration') return { type: 'Double', expr: String(v) }
  if (Array.isArray(v)) {
    return { type: '[Double]', expr: `[${v.map((n) => String(n)).join(', ')}]` }
  }
  return { type: 'String', expr: JSON.stringify(v) }
}

function isLeaf(node) {
  return node && typeof node === 'object' && '$value' in node
}

// Swift-specific source-name renames so consumer code is ergonomic.
// `type` collides with Swift's `.Type` metatype expression, even when backtick-escaped
// at declaration; rename to `typography` in this codegen target only.
const SWIFT_KEY_RENAMES = { type: 'typography' }
function aliasName(name) {
  return SWIFT_KEY_RENAMES[name] || name
}

function emitNamespace(name, node, indent) {
  const lines = [`${indent}public enum ${escapeIdent(pascalCase(aliasName(name)))} {`]
  for (const [key, child] of Object.entries(node)) {
    if (isLeaf(child)) {
      const { type, expr } = leafValue(child)
      lines.push(`${indent}  public static let ${escapeIdent(camelCase(key))}: ${type} = ${expr}`)
    } else {
      lines.push(emitNamespace(key, child, `${indent}  `))
    }
  }
  lines.push(`${indent}}`)
  return lines.join('\n')
}

function formatSwift(dict) {
  const root = dict.tokens || dict
  return `${HEADER}${emitNamespace('Tokens', root, '')}\n`
}

module.exports = { formatSwift, parseColor }
