'use strict'

const HEADER = '// @generated by tokens/scripts/build.js — do not edit\n\n'

function isLeaf(node) {
  return node && typeof node === 'object' && '$value' in node
}

function emitValue(value) {
  if (typeof value === 'number') return String(value)
  if (typeof value === 'string') return JSON.stringify(value)
  if (Array.isArray(value)) return JSON.stringify(value)
  if (value === null || value === undefined) return 'null'
  return JSON.stringify(value)
}

function emitNode(node, indent) {
  if (isLeaf(node)) {
    return emitValue(node.$value)
  }
  const lines = ['{']
  const keys = Object.keys(node)
  keys.forEach((key, i) => {
    const keyOut = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key) ? key : JSON.stringify(key)
    const child = emitNode(node[key], `${indent}  `)
    const trail = i < keys.length - 1 ? ',' : ''
    lines.push(`${indent}  ${keyOut}: ${child}${trail}`)
  })
  lines.push(`${indent}}`)
  return lines.join('\n')
}

function formatTypeScript(dict) {
  const root = dict.tokens || dict
  return `${HEADER}export const tokens = ${emitNode(root, '')} as const\n\nexport type Tokens = typeof tokens\n`
}

module.exports = { formatTypeScript }
