/**
 * Centralized error codes for Convex functions.
 * All error codes must be defined here and referenced elsewhere.
 */
export const ERROR_CODES = {
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  FORBIDDEN: 'FORBIDDEN',
  AGENT_RESPONSE_INVALID: 'AGENT_RESPONSE_INVALID',
  NO_ROUTES_GENERATED: 'NO_ROUTES_GENERATED',
  AGENT_TIMEOUT: 'AGENT_TIMEOUT',
  INVALID_AGENT_RESPONSE_STRUCTURE: 'INVALID_AGENT_RESPONSE_STRUCTURE',
  PLAN_ALREADY_ACTIVE: 'PLAN_ALREADY_ACTIVE',
  PLAN_NOT_FOUND: 'PLAN_NOT_FOUND',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  LOW_CONFIDENCE_PARSE: 'LOW_CONFIDENCE_PARSE',
  NETWORK_TIMEOUT: 'NETWORK_TIMEOUT',
  WEATHER_UNAVAILABLE: 'WEATHER_UNAVAILABLE',
  GENERATION_FAILED: 'GENERATION_FAILED',
  AGENTIC_PARSE_FAILED: 'AGENTIC_PARSE_FAILED',
  PLAN_LIMIT_EXCEEDED: 'PLAN_LIMIT_EXCEEDED',
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  INVALID_CONTENT: 'INVALID_CONTENT',
  AGENT_BUDGET_EXCEEDED: 'AGENT_BUDGET_EXCEEDED',
  AGENT_LOOP_DETECTED: 'AGENT_LOOP_DETECTED',
} as const

/**
 * Type alias for error code values
 */
export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES]
