import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import ts from 'typescript'

export type ParsedConvexApiTypes = {
  apiPath: string
  moduleImports: string[]
}

export type GenerateMobileTypesResult = {
  swiftOutputPath: string
  kotlinOutputPath: string
  swiftSource: string
  kotlinSource: string
  tableNames: string[]
}

function resolveServerDir(cwd: string): string {
  return cwd.endsWith(`${path.sep}server`) ? cwd : path.resolve(cwd, 'server')
}

function resolveRepoRoot(cwd: string): string {
  const serverDir = resolveServerDir(cwd)
  return path.dirname(serverDir)
}

export function parseConvexApiTypes(
  apiPath = path.resolve(resolveServerDir(process.cwd()), 'convex/_generated/api.d.ts'),
): ParsedConvexApiTypes {
  const sourceText = readFileSync(apiPath, 'utf8')
  const sourceFile = ts.createSourceFile(apiPath, sourceText, ts.ScriptTarget.Latest, true)

  const moduleImports: string[] = []
  for (const statement of sourceFile.statements) {
    if (!ts.isImportDeclaration(statement)) {
      continue
    }
    if (!ts.isStringLiteral(statement.moduleSpecifier)) {
      continue
    }
    moduleImports.push(statement.moduleSpecifier.text)
  }

  return { apiPath, moduleImports }
}

function toPascalCase(input: string): string {
  return input
    .split('_')
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('')
}

function parseTableNames(schemaPath: string): string[] {
  const schemaText = readFileSync(schemaPath, 'utf8')
  const tableNames = new Set<string>()
  const matches = schemaText.matchAll(/^\s{2}([a-z_]+):\s*defineTable\(/gm)
  for (const match of matches) {
    tableNames.add(match[1] ?? '')
  }
  return Array.from(tableNames).filter(Boolean)
}

function generateSwiftSource(tableNames: string[]): string {
  const structs = tableNames
    .map((tableName) => {
      const structName = `${toPascalCase(tableName)}Document`
      return `public struct ${structName}: Codable {}\n`
    })
    .join('\n')

  return `// Generated by server/scripts/generate-mobile-types.ts. Do not edit.
import Foundation

${structs}`
}

function generateKotlinSource(tableNames: string[]): string {
  const classes = tableNames
    .map((tableName) => {
      const className = `${toPascalCase(tableName)}Document`
      return `@Serializable\ndata class ${className}(\n  val _id: String? = null,\n  val _creationTime: Long? = null,\n)\n`
    })
    .join('\n')

  return `// Generated by server/scripts/generate-mobile-types.ts. Do not edit.
package com.laneshadow.generated

import kotlinx.serialization.Serializable

${classes}`
}

export function generateMobileTypes(rootDir = process.cwd()): GenerateMobileTypesResult {
  const repoRoot = resolveRepoRoot(rootDir)
  const serverDir = resolveServerDir(rootDir)
  parseConvexApiTypes(path.resolve(serverDir, 'convex/_generated/api.d.ts'))
  const tableNames = parseTableNames(path.resolve(serverDir, 'convex/schema.ts'))

  const swiftSource = generateSwiftSource(tableNames)
  const kotlinSource = generateKotlinSource(tableNames)

  const swiftOutputPath = path.resolve(
    repoRoot,
    'ios/LaneShadow/Generated/ConvexTypes.generated.swift',
  )
  const kotlinOutputPath = path.resolve(
    repoRoot,
    'android/app/src/main/java/com/laneshadow/generated/ConvexTypes.kt',
  )

  mkdirSync(path.dirname(swiftOutputPath), { recursive: true })
  mkdirSync(path.dirname(kotlinOutputPath), { recursive: true })
  writeFileSync(swiftOutputPath, swiftSource)
  writeFileSync(kotlinOutputPath, kotlinSource)

  return { swiftOutputPath, kotlinOutputPath, swiftSource, kotlinSource, tableNames }
}

if (process.argv[1]?.endsWith('generate-mobile-types.ts')) {
  generateMobileTypes()
}
